### ISSUE TITLE
multi threading not working

### ISSUE THREAD

**Issue by brooksambrose** [markvanderloo/stringdist#27]
Since the move to openMP I can't get stringdist to run on more than one core. When nthreads is set to 2, 3, or 4 (my max) I can tell from activity monitor that only one core is active. I've reinstalled gcc and checked that openMP is working elsewhere; I can't figure out what's wrong! Wondering if this is a known issue or just me.

```
> getOption("sd_num_thread")
[1] 3
> parallel::detectCores()
[1] 4
> sessionInfo(package = NULL)
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringdist_0.9.0

loaded via a namespace (and not attached):
[1] parallel_3.1.3 tools_3.1.3   
```

**Comment by markvanderloo** [comment]
hmm, I can't really explain that and since I don't have an apple computer I can't reproduce it. 

The writing R extensions manual has the following to say about [openMP support](http://cran.r-project.org/doc/manuals/r-release/R-exts.html#OpenMP-support) 

_As from OS X 10.9 clang is used, and the Apple builds currently have no OpenMP support._

I think perhaps you need to compile R itself with gcc (if that works on apple -- I don't know) and then build stringdist using R CMD build.

--edit-- Just found (this thread)[https://groups.google.com/forum/#!topic/rdevtools/tVeRXvOv-fc]. It might help

**Comment by pommedeterresautee** [comment]
Check xgboost repository on github. It uses openmp too and instruction to make it work on Apple is described.
It should work for any openmp package.


Kind regards,
Michaël
