### ISSUE TITLE
Multiprocessor support on Mavericks

### ISSUE THREAD

**Issue by davidkip** [markvanderloo/stringdist#36]
Hi

Version 0.8.x would spawn multiple R processes and use all my 24 cores on my Mac under R3.2.1. Version 0.9.x instead spawns multiple threads, not processes.  Looking at the Activity Monitor it's clear it's just using a single core (and the runtime confirms that).

I've reverted to 0.8.x in the meantime.

**Comment by markvanderloo** [comment]
That's because according to [writing R extensions](http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#OpenMP-support):

```
OS X nowadays uses clang, and the Apple builds currently have no OpenMP support.
```
I've switched to openmp because it is way more efficient than ```parallel``` which spawns multiple R sessions. You can still do that yourself however. It is not difficult, here's an example:

```
cl <- cluster(3)
m <- parSapply(cl,b,stringdist, a=a, method="osa")
stopCluster(cl)
```
just note that I parallelize over b because of the way ```parSapply``` simplifies things into an array.

**Comment by davidkip** [comment]
Oh that's annoying of OS X!  Thanks for clearly that up Mark.

**Comment by markvanderloo** [comment]
You're welcome! 

Another advantage of openmp is that I can easily low-level parallelize stringdist (not just stringdistmatrix) and amatch as well. with a lot less code overhead.
