### ISSUE TITLE
Local alignment

### ISSUE THREAD

**Issue by feuerbach** [markvanderloo/stringdist#49]
Would you be open to including a local alignment metric (https://en.wikipedia.org/wiki/Smith%E2%80%93Waterman_algorithm)? I could prepare a patch.

**Comment by markvanderloo** [comment]
Sure, I'm happy to receive contributions. But please have it fit in the current infrastructure. All core algo's are C99 implemetations that work on int arrays. Translating strings to ints happens in preprocessing. Also the core algo should be callable by multiple threads since the loops are openMP'd.
