### ISSUE TITLE
MaxDist?

### ISSUE THREAD

**Issue by swuecho** [markvanderloo/stringdist#50]
sometimes only care about the distance blow a max value.

postgres has this.
```
levenshtein_less_equal(text` source, text target, int max_d) returns int
```

https://www.postgresql.org/docs/9.1/static/fuzzystrmatch.html

I check the document of this package, indicate the MaxDist is deprecated.

**Comment by markvanderloo** [comment]
indeed. I chose performance over the maxDist option. It adds several if-branches to the core algorithm. Doesn't sound like much but since the core algo is really only shifting a few ints around, it adds up very quickly. It would only be really be beneficial for really long strings. But in that case, another distance measure is probably better (i.e. q-gram based).
